### ISSUE TITLE
Metamagic adept feat bug?

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2171]
I picked metamagic adept and the empowered spell option, description said my CHA attribute would get a +1 but I didn't see the addition. My Warlock is originally CHA 17 and after this process he is still 17.

**Comment by NathanNN** [comment]
[Lev.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10414084/Lev.zip)

The campaign im playing is Vel Leverage Remaster.

**Comment by ThyWoof** [comment]
Not a bug. This was OP but description was fixed.

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaUnfinishedBusiness/Translations/en/Feats/Metamagic-en.txt

**Comment by NathanNN** [comment]
Still say +1 to CHA as of .35
![Uploading C4109CFC-D9BC-40D8-96BF-5353F754632C.jpeg…]()

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/212497780-32ba6fde-9afd-4c45-bb25-b6e2c016ba78.png)
your installation is broken. Manually download mod and reinstall from zip.

**Comment by NathanNN** [comment]
hmm I still see that line of text with a complete uninstall of mod and fresh install from the zip here.
