### ISSUE TITLE
Weapon proficiencies not correctly applied by feats granting multiple weapon proficiencies.

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#2946]
Hi, 
I've been playing a Monk, selected new weapons as "monk" weapons - but that doesn't provide the appropriate proficiency for it (which is a bit weird IMO, but I'm ok if it's RAW).

During the main campaign I tried
- adding the FeatBladeMastery from the Party Editor
- picking the BladeMastery feat as any player could do when allowed to choose a new feat.

same applies to other feats granting proficiency to a set of weapons.

I have no other mods installed. (SUB v1.4.33.71)

Wishlist: - add -all- the feats to the list (simple weap. proficiency, martial weap. proficiency), including the pseudoinvocations.
I have a CustomInvocationMonkWeaponSpecializationScimitarType in my invocations list. I understand this is some sort of workaround but you can't really pick a specialization or any feat requiring a choice with the current editor.
Suggestion: add a "add X bonus feats for player Y on next level up" Button - to at least delegate choosing a spell or a weapon on next level up.

**Comment by ThyWoof** [comment]
I touched this on .72. Can you try there?

**Comment by ThyWoof** [comment]
Fixed in dev

**Comment by NeatWolf** [comment]
Tried that yesterday on .72 but the issue was still there. Today I'll be playing with the .73 but I wish there was an easier way to add a single bonus feat, in game, using the game UI, just for debugging. 
I'm not sure if adding the feat via SUB's edit party feat list applies all the changes related to picking each feat properly (it doesn't when a talent requires to also pick a choice/feat on another in-game screen)

**Comment by NeatWolf** [comment]
> I touched this on .72. Can you try there?
As per .74, the monk specialization considers the monk proficient in the chosen weapons. Works for me.

Yet, feats like the ones granting multiple proficiencies (mentioned above) look like they still don't provide the benefits listed in the descriptions.
