### ISSUE TITLE
Saving Issues

### ISSUE THREAD

**Issue by MarinerEarendil** [SolastaMods/SolastaUnfinishedBusiness#3989]
Been having issues with saving, both manually and autosave on current campaign (Island of Domination). Get errors sometimes while manually saving, sometimes when moving between locations triggers an autosave, and sometimes when the end of a fight triggers an autosave.

No save file since the manual save error seems to "wipe" the old save if overwriting (good thing I keep backups) but here is a .log file:

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12566891/Player.log)

**Comment by ThyWoof** [comment]
Do you have a save before exiting a location? Got other reports that it happens more often under that scenario.

**Comment by ThyWoof** [comment]
Also, do you have an Aasimar?

**Comment by MarinerEarendil** [comment]
I don't have a save before entering a new location but I do have a successful save from before I tried another save to backup and it threw an error (saving twice back to back, second time threw the error and erased the save).
Team is Oligath Yeoman Barbarian, Sylvan Elf Distant Hand Monk, High Elf Arcane Archer Fighter, and Half-Elf Arcane Trickster Rogue.
Active buffs=Longstrider, Light cantrip, Deadeye

Save file and .log file:
[merrymen_islandofdomination_bu.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12572156/merrymen_islandofdomination_bu.zip)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12572157/Player.log)

**Comment by ThyWoof** [comment]
I released a DEBUG version with v14 with the hope I can get better logs with line numbers. Fully reproduced the original TA code in mod to better understand what breaks. Please update to v14 and update this ticket if you face the bug again.

**Comment by MarinerEarendil** [comment]
Got it, I'll post another save and log if it happens after the update. Sorry I can't give more details but the error seems pretty random--fights with different enemies, loading into different environments, etc

Thanks again for the mod development and bugfixing.

**Comment by kosocku** [comment]
I've updated to v14, and I'm having the same issue.  Try to save a game, get the error message to send the player log and the save file I'm trying to overwrite is gone.  Before trying to manual save, auto-save seems to work fine.  I've attached the latest autosave file along with the players and the player.log

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12640938/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
This save was made on v13. Couldn’t reproduce on v14. Any steps I should take?Sent from my iPhoneOn Sep 16, 2023, at 7:57 AM, kosocku ***@***.***> wrote:﻿
I've updated to v14, and I'm having the same issue.  Try to save a game, get the error message to send the player log and the save file I'm trying to overwrite is gone.  Before trying to manual save, auto-save seems to work fine.  I've attached the latest autosave file along with the players and the player.log
UB Bug reports.zip

**Comment by MarinerEarendil** [comment]
Had another couple issues, here are two player logs and the accompanying saves files.  Still not seeing any pattern here--one error showed up while autosaving after a fight, another showed up while doing a manual save.


Here's the sequence as I can remember for this set:
1. Short rest. Activate identify power.
2. Enter new location.
3. Start fight. Autosave works as normal.
4. End fight. Autosave triggers error.
The save file here is the autosave from the start of the fight.
[AutoSave_Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12643006/AutoSave_Player.log)
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12643007/AutoSave_1.zip)



This error came up while manually saving, on the second save as I normally make two per campaign.
[RedCrow_Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12643008/RedCrow_Player.log)
[red_crow_test_backup.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12643009/red_crow_test_backup.zip)


Looking at the two Player.log files, they seem to have similar errors at the end?

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5508759f-6e98-4138-86ac-075c27657947)
trying my best to reproduce on my end but cannot.

**Comment by ThyWoof** [comment]
I put tons of log info in that method to better understand what’s going on. V15 should tell us what’s going on.

**Comment by ThyWoof** [comment]
@MarinerEarendil , I put lots of logs on this method to learn exactly where it breaks. Can you have v15 installed and share new logs and save once it happens again?

**Comment by MarinerEarendil** [comment]
Sounds good.  I haven't had any saving issues on v15 yet, so perhaps some behind the scenes stability changes fixed it?  I also haven't played the first campaign where the issue showed up so I should try that some point.

The only other thing I can think of that's different is I am not using the "Identify after a rest" power since I have the spell as a ritual. So that might be worth a look.
